name: qai-drug-ml
channels:
  - conda-forge
  - pytorch
  - pyg
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pyyaml
  - requests
  - tqdm
  - openbabel
  - openmm
  - pdbfixer
  - pytorch
  - rdkit
  - pip:
      - -e .
      - torch-geometric
      - fastapi
      - uvicorn
      - pydantic
      - py3Dmol
      - qiskit
      - pyarrow
      - httpx
      - pytest
