from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


RESOURCE_REGISTRY: list[dict[str, Any]] = [
    {
        "id": "chembl",
        "name": "ChEMBL",
        "category": "bioactivity",
        "priority": "P0 core",
        "access": "API, paginated exports, target-sliced local cache",
        "license_note": "CC-BY-SA lineage; keep attribution and share-alike review in client deployments.",
        "source_url": "https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services",
        "local_checks": ["outputs/cancer_proof_v1/assets/ligand_asset_manifest.csv", "data/raw/chembl*"],
        "value": "Assay-level compound, target, activity, mechanism, drug indication, warning, and structure assets.",
        "next_action": "Keep target-level slices local; add assay confidence filters and organism/protein-complex normalization before model training.",
    },
    {
        "id": "bindingdb",
        "name": "BindingDB",
        "category": "bioactivity",
        "priority": "P0 core",
        "access": "Target query and optional full TSV ZIP mirror",
        "license_note": "BindingDB-curated and imported records have different Creative Commons lineage; store source rows and attribution.",
        "source_url": "https://www.bindingdb.org/rwd/bind/info.jsp",
        "local_checks": ["data/raw/BindingDB_All.tsv.zip", "data/raw/bindingdb*"],
        "value": "Experimental Ki, IC50, Kd, EC50, thermodynamic and target-ligand data for SAR and affinity calibration.",
        "next_action": "Prefer target slices for default installs; full mirror should be an explicit data-admin operation.",
    },
    {
        "id": "pubchem",
        "name": "PubChem",
        "category": "chemistry",
        "priority": "P0 core",
        "access": "PUG-REST connector and local query cache",
        "license_note": "Public NIH service; respect request policies and preserve upstream source identifiers.",
        "source_url": "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
        "local_checks": ["data/processed/reference_inhibitors.csv", "user-front/public/pharma-library/ligands/chembl/search/*.json"],
        "value": "Compound identifiers, synonyms, properties, bioassay links, and cross-reference enrichment.",
        "next_action": "Add CID/InChIKey canonical cache and crosswalk ChEMBL, BindingDB, DrugCentral, and PDB ligands.",
    },
    {
        "id": "rcsb-pdb",
        "name": "RCSB PDB",
        "category": "structure",
        "priority": "P0 core",
        "access": "Data/Search/ModelServer APIs plus curated receptor artifacts",
        "license_note": "Public PDB archive; cite wwPDB/RCSB and structure-specific primary references.",
        "source_url": "https://www.rcsb.org/docs/programmatic-access/web-apis-overview",
        "local_checks": ["outputs/cancer_proof_v1/docking/prepared_receptors/*.pdb", "configs/oncology_pockets.yaml"],
        "value": "Co-crystal receptors, ligands, cofactors, waters, and pocket anchors for credible docking grids.",
        "next_action": "Expand pocket registry with redocking RMSD controls, cofactors, conserved waters, alternate chains, and mutation mapping.",
    },
    {
        "id": "alphafold-db",
        "name": "AlphaFold DB",
        "category": "structure",
        "priority": "P0 core",
        "access": "Selected UniProt structures, PAE, metadata; never bulk mirror by default",
        "license_note": "CC-BY-4.0 with EMBL-EBI attribution; full database is too large for default local installs.",
        "source_url": "https://github.com/google-deepmind/alphafold/blob/main/afdb/README.md",
        "local_checks": ["user-front/public/pharma-library/receptors/alphafold/*model_v6.cif"],
        "value": "Predicted receptor models and confidence metadata when experimental structures are absent.",
        "next_action": "Add pLDDT/PAE pocket suitability gates and prefer PDB holo anchors whenever possible.",
    },
    {
        "id": "uniprot",
        "name": "UniProt",
        "category": "target-biology",
        "priority": "P0 core",
        "access": "REST API, ID mapping, target metadata cache",
        "license_note": "Open scientific resource; preserve accession, isoform, and release metadata.",
        "source_url": "https://www.uniprot.org/help/programmatic_access",
        "local_checks": ["configs/cancer_targets.yaml", "user-front/public/pharma-library/receptors/alphafold/*metadata.json"],
        "value": "Sequence, isoform, domain, function, disease annotation, and cross-reference grounding.",
        "next_action": "Add isoform-aware receptor selection, mutation-to-domain mapping, and target family liabilities.",
    },
    {
        "id": "open-targets",
        "name": "Open Targets Platform",
        "category": "target-biology",
        "priority": "P0 core",
        "access": "GraphQL/API and versioned data downloads",
        "license_note": "Open dataset stack with source-specific provenance; store release IDs.",
        "source_url": "https://platform.opentargets.org/downloads",
        "local_checks": ["data/research_resources/open_targets/*"],
        "value": "Target-disease evidence, genetics, tractability, safety, pathway, and prioritization signals.",
        "next_action": "Add disease-target association retrieval for selected diagnosis and target rationale scoring.",
    },
    {
        "id": "moleculenet",
        "name": "MoleculeNet / DeepChem Benchmarks",
        "category": "ml-benchmarks",
        "priority": "P0 core",
        "access": "Small benchmark CSV mirrors",
        "license_note": "Dataset-specific licenses; keep source and citation manifest with every file.",
        "source_url": "https://deepchem.readthedocs.io/en/latest/api_reference/moleculenet.html",
        "local_checks": ["data/research_resources/moleculenet/*"],
        "value": "ADMET, toxicity, solubility, permeability, HIV, BACE, and molecular property model validation.",
        "next_action": "Use as regression/classification smoke benchmarks, not as pharma-grade endpoint substitutes.",
    },
    {
        "id": "realtime-data-fabric",
        "name": "Realtime Evidence Fabric",
        "category": "data-orchestration",
        "priority": "P0 core",
        "access": "Backend connector and TTL cache for ChEMBL, PubChem, UniProt, Open Targets, RDKit, and AI model hooks",
        "license_note": "Connector outputs inherit source-specific licenses; store source URLs, cache timestamps, and redistribution boundaries.",
        "source_url": "/v1/research/data-fabric/status",
        "local_checks": ["data/research_resources/realtime_cache/*"],
        "value": "Live target/ligand enrichment, assay coverage counts, identity crosswalks, descriptors, and model-hook readiness for current workspace state.",
        "next_action": "Add background refresh queues, dataset cards per cache key, and model-calibrated evidence-quality multipliers.",
    },
    {
        "id": "tdc",
        "name": "Therapeutics Data Commons",
        "category": "ml-benchmarks",
        "priority": "P1 expansion",
        "access": "Python package with task-specific loaders and leaderboards",
        "license_note": "TDC code is MIT; individual dataset licenses must be reviewed per task.",
        "source_url": "https://tdcommons.ai/",
        "local_checks": ["data/research_resources/tdc/*"],
        "value": "Standardized tasks for ADMET, DTI, docking, drug combination, trial outcome, and therapeutic ML evaluation.",
        "next_action": "Add TDC loader wrapper with dataset-card and split-strategy capture.",
    },
    {
        "id": "depmap",
        "name": "DepMap / CCLE / PRISM",
        "category": "cancer-functional-genomics",
        "priority": "P1 expansion",
        "access": "Release downloads and file-specific licensing",
        "license_note": "License is file-specific in DepMap downloads; require explicit source manifest before client redistribution.",
        "source_url": "https://depmap.org/",
        "local_checks": ["data/research_resources/depmap/*"],
        "value": "Cancer dependencies, CRISPR screens, expression, mutation, copy number, proteomics, and drug response context.",
        "next_action": "Add diagnosis-to-cell-line cohort matching, dependency support, and resistance marker scoring.",
    },
    {
        "id": "gdsc",
        "name": "GDSC / CancerRxGene",
        "category": "cancer-functional-genomics",
        "priority": "P1 expansion",
        "access": "Website downloads and versioned drug-response tables",
        "license_note": "Academic/open resource; verify usage terms before commercial redistribution.",
        "source_url": "https://www.sanger.ac.uk/tool/gdsc-genomics-drug-sensitivity-cancer/",
        "local_checks": ["data/research_resources/gdsc/*"],
        "value": "Cancer cell-line drug sensitivity and biomarker associations for translational prioritization.",
        "next_action": "Add IC50/AUC response model calibration and tissue-context evidence cards.",
    },
    {
        "id": "lincs-cmap",
        "name": "LINCS / CMap L1000",
        "category": "perturbation-omics",
        "priority": "P1 expansion",
        "access": "GEO/BigQuery/GCTx connector; Level 5 signatures by default",
        "license_note": "Respect Broad/LINCS terms; large files should be cached outside source control.",
        "source_url": "https://clue.io/connectopedia/?search=L1000",
        "local_checks": ["data/research_resources/lincs/*"],
        "value": "Perturbational transcriptomic signatures for mechanism, reversal, and off-target hypotheses.",
        "next_action": "Add disease-signature reversal and pathway concordance scoring.",
    },
    {
        "id": "zinc-enamine",
        "name": "ZINC / Enamine-like purchasable space",
        "category": "screening-library",
        "priority": "P1 expansion",
        "access": "Subset/catalog connector, not full local mirror",
        "license_note": "Catalog terms vary; keep vendor/download terms and purchasability timestamp.",
        "source_url": "https://zinc20.docking.org/",
        "local_checks": ["data/research_resources/screening_libraries/*"],
        "value": "Make hit discovery actionable by searching make-on-demand or purchasable chemical space.",
        "next_action": "Add target-ready library slicing, diversity picking, and stock/vendor provenance.",
    },
    {
        "id": "gnina",
        "name": "GNINA",
        "category": "docking-ai",
        "priority": "P0 core",
        "access": "Local executable or container",
        "license_note": "Apache/GPL lineage; review deployment packaging.",
        "source_url": "https://github.com/gnina/gnina",
        "local_checks": ["outputs/cancer_proof_v1/gnina/results.csv"],
        "value": "CNN-scored docking and pose-confidence evidence beyond classical Vina-style scoring.",
        "next_action": "Require redocking controls, CNN pose thresholds, and pose/receptor coordinate validation before ranking claims.",
    },
    {
        "id": "diffdock",
        "name": "DiffDock",
        "category": "docking-ai",
        "priority": "P1 edge",
        "access": "Optional GPU model/service adapter",
        "license_note": "MIT code; model/runtime dependencies and deployment terms must be pinned.",
        "source_url": "https://github.com/gcorso/DiffDock",
        "local_checks": ["models/diffdock/*"],
        "value": "Diffusion-based pose generation as an orthogonal docking ensemble member.",
        "next_action": "Add adapter, confidence calibration against PDBBind/redocking, and disagreement-aware consensus ranking.",
    },
    {
        "id": "unimol",
        "name": "Uni-Mol / Uni-Mol2",
        "category": "foundation-model",
        "priority": "P1 edge",
        "access": "Optional pretrained molecular and pocket encoders",
        "license_note": "Check model and dependency licenses before commercial packaging.",
        "source_url": "https://github.com/deepmodeling/Uni-Mol",
        "local_checks": ["models/unimol/*"],
        "value": "3D molecular and pocket representations for property prediction, affinity scoring, and scaffold hopping.",
        "next_action": "Add embedding service and benchmark against current RDKit/QML features on held-out target families.",
    },
    {
        "id": "chemprop",
        "name": "Chemprop / message-passing molecular models",
        "category": "foundation-model",
        "priority": "P1 edge",
        "access": "Optional local model package or API adapter",
        "license_note": "Open-source package, but trained model weights and endpoint data terms must be reviewed separately.",
        "source_url": "https://github.com/chemprop/chemprop",
        "local_checks": ["models/chemprop/*", "models/**/*chemprop*"],
        "value": "Molecular property, ADMET, and activity prediction layer trained/evaluated against local and public assay datasets.",
        "next_action": "Add model-card gated inference endpoint and compare against RDKit baselines on scaffold splits.",
    },
    {
        "id": "esm-family",
        "name": "ESM protein language models",
        "category": "foundation-model",
        "priority": "P1 edge",
        "access": "NVIDIA/Hugging Face/API adapter",
        "license_note": "Model-specific terms; do not bundle weights without review.",
        "source_url": "https://github.com/facebookresearch/esm",
        "local_checks": ["models/esm*"],
        "value": "Protein sequence embeddings, variant-context features, and structure/function priors.",
        "next_action": "Cache embeddings per UniProt isoform and expose variant effect uncertainty.",
    },
    {
        "id": "diffusiongemma",
        "name": "DiffusionGemma 26B A4B IT",
        "category": "foundation-model-vision",
        "priority": "P1 edge",
        "access": "NVIDIA OpenAI-compatible chat-completions endpoint gated by DGEMMA_API_KEY",
        "license_note": "Use through NVIDIA API terms; keep key backend-only and do not claim docking validation from visual review.",
        "source_url": "https://build.nvidia.com/google/diffusiongemma-26b-a4b-it",
        "local_checks": ["models/diffusiongemma/*"],
        "value": "Multimodal review layer for docking screenshots, provenance QA, visible pose-placement bugs, and researcher-facing explanations.",
        "next_action": "Benchmark against known bad/good docking scenes and use as QA triage only, never as affinity or pose-validation proof.",
    },
    {
        "id": "medgemma",
        "name": "MedGemma 1.5 4B IT",
        "category": "medical-foundation-model",
        "priority": "P1 edge",
        "access": "Private/local OpenAI-compatible endpoint after accepting Hugging Face Health AI Developer Foundation terms",
        "license_note": "Hugging Face access requires accepting model-specific Health AI Developer Foundation terms before downloading or serving.",
        "source_url": "https://huggingface.co/google/medgemma-1.5-4b-it",
        "local_checks": ["models/medgemma/*"],
        "value": "Optional biomedical text/image reviewer for research documentation, visual QA second opinions, and medical-language summarization with strict non-clinical boundaries.",
        "next_action": "Evaluate against internal biomedical-document and visual-QA test cases before enabling for client deployments.",
    },
    {
        "id": "xtb",
        "name": "xTB / GFN2-xTB",
        "category": "quantum-qm",
        "priority": "P0 core",
        "access": "Local executable through WSL/conda",
        "license_note": "LGPL/GPL package lineage; deployment packaging needs review.",
        "source_url": "https://github.com/grimme-lab/xtb",
        "local_checks": ["outputs/cancer_proof_v1/qm/qm_descriptors.csv", "qm/*"],
        "value": "Fast semiempirical QM descriptors for orbital, dipole, charge, and conformer energetics.",
        "next_action": "Add xTB availability check, failure triage, and conformer ensemble QM rather than single-conformer only.",
    },
    {
        "id": "psi4-openfermion-qiskit",
        "name": "Psi4 + OpenFermion + Qiskit",
        "category": "quantum-qm",
        "priority": "P1 edge",
        "access": "Optional high-accuracy QM and quantum-algorithm sandbox",
        "license_note": "Open-source components with distinct licenses; package separately from default runtime.",
        "source_url": "https://github.com/psi4/psi4/",
        "local_checks": ["models/qml/*", "outputs/cancer_proof_v1/qml/*"],
        "value": "Higher-accuracy QM validation and quantum kernel/algorithm research beyond classical descriptors.",
        "next_action": "Keep QML honest with classical baselines, ablations, uncertainty, and no quantum-advantage claims without benchmarks.",
    },
]


GAP_MATRIX: list[dict[str, str]] = [
    {
        "priority": "P0",
        "area": "Data governance",
        "current": "Useful assets exist, but provenance is split across outputs, public assets, and ad hoc notices.",
        "needed": "Versioned resource registry, dataset cards, source licenses, checksums, refresh dates, and client redistribution flags.",
    },
    {
        "priority": "P0",
        "area": "Evidence calibration",
        "current": "Ranks combine activity, docking, ADMET, QM, and MD-like signals.",
        "needed": "Held-out benchmark suites, redocking RMSD, retrospective enrichment, uncertainty intervals, and evidence-quality multipliers.",
    },
    {
        "priority": "P0",
        "area": "Structure preparation",
        "current": "Curated PDB pockets exist for a small oncology panel.",
        "needed": "Protonation states, tautomers, cofactors, waters, metal handling, alternate chains, mutations, covalent modes, and pocket suitability checks.",
    },
    {
        "priority": "P0",
        "area": "ADMET and safety",
        "current": "Tox21/ClinTox-style baseline and safety panel hypotheses exist.",
        "needed": "hERG, CYP inhibition/induction, transporter, microsomal clearance, solubility, permeability, plasma protein binding, genotox, mitochondrial and endocrine panels.",
    },
    {
        "priority": "P1",
        "area": "Functional genomics",
        "current": "Patient text and selected targets drive context.",
        "needed": "Open Targets, DepMap, GDSC/PRISM, LINCS and pathway signatures for disease-relevant target and response evidence.",
    },
    {
        "priority": "P1",
        "area": "Generative and library search",
        "current": "Local generation and reference ligand panels exist.",
        "needed": "Purchasable-space search, retrosynthesis, reaction feasibility, novelty/IP checks, diversity selection, and constrained scaffold optimization.",
    },
    {
        "priority": "P1",
        "area": "Physics depth",
        "current": "Fast docking, GNINA, and lightweight OpenMM/xTB-like layers exist.",
        "needed": "MM/GBSA, FEP planning/execution hooks, protein flexibility, water networks, ensemble docking, and explicit reproducibility controls.",
    },
    {
        "priority": "P1",
        "area": "Pharma operations",
        "current": "Research UI, exports, billing, auth, and tool modules exist.",
        "needed": "Audit logs, project permissions, regulated claim guardrails, LIMS/ELN export, batch queues, GPU/HPC orchestration, and validation reports.",
    },
]


def _matches(pattern: str) -> list[str]:
    root = Path.cwd()
    return sorted(path.as_posix() for path in root.glob(pattern) if path.exists())


def _resource_status(resource: dict[str, Any]) -> dict[str, Any]:
    matches: list[str] = []
    for pattern in resource.get("local_checks", []):
        matches.extend(_matches(pattern))
    unique_matches = sorted(set(matches))
    return {
        "local_status": "present" if unique_matches else "connector",
        "local_match_count": len(unique_matches),
        "local_examples": unique_matches[:5],
    }


def research_resource_registry() -> dict[str, Any]:
    resources = [{**resource, **_resource_status(resource)} for resource in RESOURCE_REGISTRY]
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "resources": resources,
        "gaps": GAP_MATRIX,
        "summary": {
            "resource_count": len(resources),
            "local_count": sum(1 for resource in resources if resource["local_status"] == "present"),
            "connector_count": sum(1 for resource in resources if resource["local_status"] != "present"),
            "p0_count": sum(1 for resource in resources if str(resource["priority"]).startswith("P0")),
            "p1_count": sum(1 for resource in resources if str(resource["priority"]).startswith("P1")),
        },
    }
